# OLED_ENABLE = yes
# OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes

# DYNAMIC_MACRO_ENABLE = no

# EXTRAKEY_ENABLE = yes
# CONSOLE_ENABLE = yes
# COMBO_ENABLE = yes	
# KEY_OVERRIDE_ENABLE = yes
# NKRO_ENABLE = yes
# CAPS_WORD_ENABLE = yes
# AUTO_SHIFT_ENABLE = yes
# REPEAT_KEY_ENABLE = no

#HAPTIC FEEBACK
HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no

MOUSEKEY_ENABLE = yes

# VPATH += keyboards/gboards/
# SRC   += g/engine.c 


